# Model Trial #1
## Purpose: 
The purpose of this trial will be to explore the potential of machine learning to predict deaths based on population density and other information related to population size. Additionally, information from states containing vaccinations was purposely withheld in order to assess its influences of the predictive abilites of the model.

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [4]:
#Creating a DataFrame using the read_excel function from pandas
df = pd.read_csv("/Users/origi/Documents/Data Bootcamp/Final Challenge/Research Data/covid_final_data.csv")

#Showing all 50 points of data from the DataFrame
df.head(50)

,state,infected,deaths,population,pop_density,gini,icu_beds,unemployment,hospitals,health_spending,pollution,Med-large_airports
0,Alabama,1511092,20321,4908621,96.9221,0.4847,1533,2.7,101,7281,8.1,1.0
1,Alaska,302448,1321,734002,1.2863,0.4081,119,5.8,21,11064,6.4,1.0
2,Arizona,2264159,31244,7378494,64.9550,0.4713,1559,4.5,83,6452,9.7,1.0
3,Arkansas,943944,11970,3038999,58.4030,0.4719,732,3.5,88,7408,7.1,0.0
4,California,11171759,95620,39937489,256.3727,0.4899,7338,3.9,359,7549,12.8,9.0
5,Colorado,1649212,13426,5845526,56.4011,0.4586,1597,2.5,89,6804,6.7,1.0
6,Connecticut,885767,11317,3563077,735.8689,0.4945,674,3.8,32,9859,7.2,1.0
7,Delaware,305284,3080,982895,504.3073,0.4522,186,3.9,7,10254,8.3,0.0
8,Florida,7082717,80647,21992985,410.1256,0.4852,5604,2.8,217,8076,7.4,7.0
9,Georgia,2809555,38468,10736059,186.6719,0.4813,2508,3.1,145,6587,8.3,1.0
10,Hawaii,333547,1662,1412687,219.9419,0.4420,201,2.7,22,7299,5.4,2.0
11,Idaho,492685,5145,1826156,22.0969,0.4503,314,2.7,45,6927,6.8,0.0
12,Illinois,3734881,39498,12659682,228.0243,0.4810,3144,3.4,187,8262,9.3,2.0
13,Indiana,1912563,24557,6745354,188.2810,0.4527,1861,3.1,132,8300,8.4,1.0
14,Iowa,850932,9994,3179849,56.9284,0.4451,545,2.8,118,8200,7.1,0.0
15,Kansas,873582,9072,2910357,35.5968,0.4550,767,3.1,139,7651,7.0,0.0
16,Kentucky,1574948,16822,4499692,113.9566,0.4813,1392,4.2,105,8004,8.1,1.0
17,Louisiana,1446738,17955,4645184,107.5175,0.4990,1289,5.2,158,7815,7.9,1.0
18,Maine,285670,2561,1345790,43.6336,0.4519,256,3.2,34,9531,5.9,0.0
19,Maryland,1236570,15285,6083116,626.6731,0.4499,1134,3.3,50,8602,7.7,1.0
20,Massachusetts,2021331,21536,6976597,894.4355,0.4786,1326,2.8,75,10559,6.3,1.0
21,Michigan,2804588,38317,10045029,177.6655,0.4695,2423,3.6,144,8055,8.0,1.0
22,Minnesota,1645653,13509,5700671,71.5922,0.4496,1171,3.1,127,8871,6.6,1.0
23,Mississippi,922493,12853,2989260,63.7056,0.4828,824,5.4,99,7646,7.7,0.0
24,Missouri,1648081,21552,6169270,89.7453,0.4646,1888,3.5,122,8107,7.5,2.0
25,Montana,306981,3509,1086759,7.4668,0.4667,165,3.5,56,8221,6.6,0.0
26,Nebraska,534299,4490,1952570,25.4161,0.4477,440,2.9,93,8412,7.1,1.0
27,Nevada,844294,11427,3139658,28.5993,0.4577,900,3.6,44,6714,9.0,1.0
28,New Hampshire,346949,2678,1371246,153.1605,0.4304,242,2.6,28,9589,4.4,0.0
29,New Jersey,2703340,34651,8936574,1215.1991,0.4813,1822,3.8,82,8859,8.1,1.0
30,New Mexico,615162,8499,2096640,17.2850,0.4769,340,4.8,41,7214,6.0,1.0
31,New York,6031598,70733,19440469,412.5211,0.5229,3952,3.7,166,9778,6.6,3.0
32,North Carolina,3162491,26424,10611862,218.2702,0.4780,2227,3.6,112,7264,7.2,2.0
33,North Dakota,266273,2401,761723,11.0393,0.4533,238,2.2,39,9851,4.6,0.0
34,Ohio,3096557,39576,11747694,287.5038,0.4680,3314,4.1,194,8712,8.5,3.0
35,Oklahoma,1186780,14765,3954821,57.6547,0.4645,1064,3.2,125,7627,8.2,0.0
36,Oregon,885963,8492,4301089,44.8086,0.4583,659,3.3,61,8044,7.8,1.0
37,Pennsylvania,3220994,46970,12820878,286.5449,0.4689,3169,4.7,199,9258,9.2,2.0
38,Rhode Island,420175,3652,1056161,1021.4323,0.4781,279,3.4,11,9551,7.3,0.0
39,South Carolina,1696746,18316,5210095,173.3174,0.4735,1225,2.5,69,7311,7.4,0.0
40,South Dakota,259683,3014,903027,11.9116,0.4495,152,3.3,57,8933,5.1,0.0
41,Tennessee,2263911,27267,6897576,167.2748,0.4790,2209,3.4,115,7372,7.4,1.0
42,Texas,7826318,90673,29472295,112.8204,0.4800,6199,3.5,523,6998,8.3,6.0
43,Utah,1032402,4989,3282115,39.9430,0.4063,565,2.5,54,5982,8.4,1.0
44,Vermont,141282,715,628061,68.1416,0.4539,94,2.4,14,10190,5.1,0.0
45,Virginia,2066675,21646,8626207,218.4403,0.4705,1654,2.6,96,7556,6.9,2.0
46,Washington,1796368,14195,7797095,117.3272,0.4591,1265,3.8,92,7913,8.0,1.0
47,West Virginia,593806,7351,1778070,73.9691,0.4711,653,4.9,56,9462,7.6,0.0
48,Wisconsin,1848935,15160,5851754,108.0497,0.4498,1159,3.5,133,8702,6.8,1.0
49,Wyoming,175746,1888,567025,5.8400,0.4360,102,3.7,29,8320,5.0,0.0

In [5]:
# Setting the State name as the index
s_df = df.set_index('state')
s_df.index.name = "State"
s_df.head()

,infected,deaths,population,pop_density,gini,icu_beds,unemployment,hospitals,health_spending,pollution,Med-large_airports
State,,,,,,,,,,,
Alabama,1511092,20321,4908621,96.9221,0.4847,1533,2.7,101,7281,8.1,1.0
Alaska,302448,1321,734002,1.2863,0.4081,119,5.8,21,11064,6.4,1.0
Arizona,2264159,31244,7378494,64.9550,0.4713,1559,4.5,83,6452,9.7,1.0
Arkansas,943944,11970,3038999,58.4030,0.4719,732,3.5,88,7408,7.1,0.0
California,11171759,95620,39937489,256.3727,0.4899,7338,3.9,359,7549,12.8,9.0

 **Note**:
As can be seen above, there are no string values that need to be converted into numerical values. Therefore, the next step can be proceeded with which is to create the features and target.

In [6]:
# Creating the DataFrame that contains the desired features
X = s_df.drop(columns="deaths")

# Creating the DataFrame that contains the desired target
y = pd.DataFrame(s_df["deaths"])

In [7]:
# Inspecting the dataset's statistical information. 
X.describe()

,infected,population,pop_density,gini,icu_beds,unemployment,hospitals,health_spending,pollution,Med-large_airports
count,5.000000e+01,5.000000e+01,50.000000,50.000000,50.000000,50.000000,50.000000,50.00000,50.000000,50.000000
mean,1.880679e+06,6.611966e+06,203.900898,0.464648,1489.460000,3.482000,103.760000,8259.92000,7.366000,1.240000
std,2.124986e+06,7.480025e+06,267.412842,0.021015,1569.200033,0.803739,88.799375,1157.62658,1.431513,1.767738
min,1.412820e+05,5.670250e+05,1.286300,0.406300,94.000000,2.200000,7.000000,5982.00000,4.400000,0.000000
25%,5.491758e+05,1.857760e+06,47.706725,0.451975,365.000000,2.825000,46.250000,7381.00000,6.625000,0.000000
50%,1.341654e+06,4.572438e+06,107.783600,0.467350,1146.500000,3.400000,90.500000,8091.50000,7.400000,1.000000
75%,2.214602e+06,7.692445e+06,219.566500,0.478900,1851.250000,3.800000,130.750000,8917.50000,8.100000,1.000000
max,1.117176e+07,3.993749e+07,1215.199100,0.522900,7338.000000,5.800000,523.000000,11064.00000,12.800000,9.000000

**Note**: As observed from the cell above, the variation between the columns/features is indeed large. This could have an affect on the end results and predictive abilities of the model. Therefore, using this information the features will be scaled.

### Splitting into Train and Test sets

Now that both the features and target have been inspected, it is time to split the data into training and test sets.

In [8]:
X_train = X.loc[["Alaska", "Alabama", "Arkansas", "Arizona", "California", "Colorado", "Delaware", "Florida", "Georgia", "Hawaii", "Iowa", "Idaho", "Illinois", "Indiana", "Kansas", "Kentucky", "Louisiana", "Massachusetts", "Maryland", "Maine", "Michigan", "Minnesota", "Missouri", "Mississippi", "Montana", "North Carolina", "North Dakota", "Nebraska", "New Hampshire", "New Jersey", "New Mexico", "Nevada", "New York", "Ohio", "Oklahoma", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Virginia", "Vermont", "Washington", "Wisconsin", "West Virginia", "Wyoming"]]
X_test = X.loc[["Utah", "Oregon", "Connecticut"]]
y_train = y.loc[["Alaska", "Alabama", "Arkansas", "Arizona", "California", "Colorado", "Delaware", "Florida", "Georgia", "Hawaii", "Iowa", "Idaho", "Illinois", "Indiana", "Kansas", "Kentucky", "Louisiana", "Massachusetts", "Maryland", "Maine", "Michigan", "Minnesota", "Missouri", "Mississippi", "Montana", "North Carolina", "North Dakota", "Nebraska", "New Hampshire", "New Jersey", "New Mexico", "Nevada", "New York", "Ohio", "Oklahoma", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Virginia", "Vermont", "Washington", "Wisconsin", "West Virginia", "Wyoming"], ["deaths"]]
y_test = y.loc[["Utah", "Oregon", "Connecticut"],["deaths"]]

In [9]:
# Creating StandardScaler instance
scaler = StandardScaler()

In [10]:
# Fitting Standard Scaller
X_scaler = scaler.fit(X_train)

In [11]:
# Scaling data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

### Fitting the model
By this point, the data has been split into training and test sets as well as scaled. Thus, the model is ready to be fit to the training data.

In [12]:
model = LinearRegression()
model.fit(X_train_scaled,y_train)

LinearRegression()

### Testing the model
The model has been fitted to the data. It's ready for death predictions.

In [13]:
# Make a prediction
y_pred = model.predict(X_test)
y_pred

array([[ 1.77796472e+09],
       [-2.72526304e+09],
       [-6.13443174e+08]])

In [14]:
# Showing the predicted outputs
for i in range(len(X_test_scaled)):
    index = ['Utah', 'Oregon', 'Connecticut']
    print("Predicted deaths for " +index[i]+ "= %3d" % y_pred[i][0])

Predicted deaths for Utah= 1777964720
Predicted deaths for Oregon= -2725263043
Predicted deaths for Connecticut= -613443174

### Results
The models results will now be tested for accuracy

In [15]:
# Setting up the data for analysis
Column_names = ['Predicted', 'Actual', 'State']
results = pd.DataFrame(y_pred)
results["test"] = y_test["deaths"].values
results["state"] = ['Utah', 'Oregon', 'Connecticut']
results.set_axis(Column_names, axis=1, inplace=True)

# Setting the State name as the index
y_results = results.set_index('State')
y_results.head()

                Predicted  Actual
State
Utah         1.777965e+09    4989
Oregon      -2.725263e+09    8492
Connecticut -6.134432e+08   11317

In [16]:
# Accuracy Calculations
realVals = y_results.Actual
predictedVals = y_results.Predicted

# Empty arrays holding the error data
abs_error_array = []
rel_error_array = []
per_error_array = []

# For loop that calculates the results for each state
for i in range(len(y_results)):
    abs_error_calc = round(abs(realVals[i] - predictedVals[i]))
    rel_error_calc = round(abs(((realVals[i] - predictedVals[i])/realVals[i])))
    percent_error_calc = round(abs(((realVals[i] - predictedVals[i])/realVals[i])*100))
    std_calc = round(np.std([realVals[i], predictedVals[i]]))
    abs_error_array.append(abs_error_calc)
    rel_error_array.append(rel_error_calc)
    per_error_array.append(percent_error_calc)
    
# Creating series so that the errors can be added to the main DataFrame
abs_error = pd.Series(abs_error_array)
rel_error = pd.Series(rel_error_array)
per_error = pd.Series(per_error_array)

The metrics that were evaluated to test the model's accuracy are: Absolute Error, Relative Error, and Percent Error.

$\text{Absolute Error} = |V_{A} - V_{P}|$

$\text{Relative Error} = |\frac{V_{A} - V_{P}}{V_{A}}|$

$\text{Percent Error} = |\frac{V_{A} - V_{P}}{V_{A}}|*100\%$

$\text{Nomenclature}:$
- $V_{A} = \text{Acutal/Measured Value}$
- $V_{P} = \text{Predicted/Model Value}$

In [17]:
# Adding the calculations to the results DataFrame
y_results["Absolute Error"] = abs_error.values
y_results["Relative Error"] = rel_error.values
y_results["Percent Error"] = per_error.values
y_results

,Predicted,Actual,Absolute Error,Relative Error,Percent Error
State,,,,,
Utah,1.777965e+09,4989,1777959732,356376,35637597
Oregon,-2.725263e+09,8492,2725271536,320922,32092223
Connecticut,-6.134432e+08,11317,613454491,54206,5420646

In [18]:
# Formatting the DataFrame 
y_results["Predicted"] = y_results["Predicted"].map("{:.2e}".format)
y_results["Actual"] = y_results["Actual"].map("{:.2e}".format)
y_results["Absolute Error"] = y_results["Absolute Error"].map("{:.2e}".format)
y_results["Relative Error"] = y_results["Relative Error"].map("{:.2e}".format)
y_results["Percent Error"] = y_results["Percent Error"].map("{:.2e}".format)
y_results

# Creating the output file (CSV)
output_data_file = "/Users/origi/Documents/Data Bootcamp/Final Challenge/Final Challenge Code/Trail_1_results.csv"
# Exporting the results into a CSV.
y_results.to_csv(output_data_file)

### Conclusion
The model produced extremely poor results. The analytics metrics utilized demonstrate major error with predicted when compared to the actual values. Not quite certain what would have caused this, but for **Model Trial #2** the data will not be scaled to see if this can be error can be corrected.